export class Feedback {
  id: number | null; // Optional, as the ID may be generated by the backend
  comment: string;
  responseId: number | null;
  userId: number | null;
  date: Date;
  lunchId: number;
  userName?: string; // Optional field for user name
  lunchMenu?: string; 
  response?: string;

  constructor(
    id: number = 0,
    comment: string = '',
    responseId: number = 0,
    userId: number = 0,
    date: Date = new Date(),
    lunchId: number = 0,
    userName: string = '',  // Optional parameter for user name
    lunchMenu: string = '',
    response: string = ''
  ) {
    this.id = id;
    this.comment = comment;
    this.responseId = responseId;
    this.userId = userId;
    this.date = date;
    this.lunchId = lunchId;
    this.userName = userName;
    this.lunchMenu = lunchMenu;
    this.response = response;
  }
}
