import { OrderRow } from "./orderRow";

export class Order {
    id?: number; // Optional, as it may be generated by the backend
    orderDate: Date;
    message: string;
    restaurantId: number; // Foreign key for restaurant
    adminId: number; // Foreign key for admin
    rows: OrderRow[]; // List of OrderRow objects
  
    constructor(
      id: number = 0,
      orderDate: Date = new Date(),
      message: string = '',
      restaurantId: number = 0,
      adminId: number = 0,
      rows: OrderRow[] = []
    ) {
      this.id = id;
      this.orderDate = orderDate;
      this.message = message;
      this.restaurantId = restaurantId;
      this.adminId = adminId;
      this.rows = rows;
    }
  }

export { OrderRow };
  