export class OrderRow {
    id?: number; // Optional, as it may be generated by the backend
    lunchDate: Date;
    quantity?: number;
  
    constructor(
      id: number = 0,
      lunchDate: Date = new Date(),
      quantity: number = 0
    ) {
      this.id = id;
      this.lunchDate = lunchDate;
      this.quantity = quantity;
    }
  }
  